// Auto-generated by metrics-api/src/tracker/generate_trackers.js — do not edit directly.
// To change tracker behavior, edit metrics-tracker.template.js and re-run the generator.
const METRICS_CONFIG = {
  endpoint: "https://metrics.arqing-mexico.com",
  siteId: "arqingrenders",
  projectKey: "pk_arqingrenders_dcaa3154bde3"
};

/*
 * Shared metrics tracker body — DO NOT edit per-site copies of this logic
 * directly. Edit this template, then regenerate each site's
 * frontend/js/metrics.js (see generate_trackers.js).
 *
 * Expects a `METRICS_CONFIG` object to already be defined in an earlier
 * <script> block on the page:
 *
 *   const METRICS_CONFIG = {
 *     endpoint: "https://metrics.arqing-mexico.com",
 *     siteId: "arqingrenders",
 *     projectKey: "PUBLIC_PROJECT_KEY"
 *   };
 *
 * Sends events to the central metrics API's unified POST /events route.
 * Never throws, never blocks page rendering, never breaks navigation.
 */
(function () {
  if (typeof METRICS_CONFIG === 'undefined' || !METRICS_CONFIG.endpoint || !METRICS_CONFIG.siteId) {
    return; // misconfigured include — fail silently, don't break the page
  }
  if (window.__metricsTrackerLoaded) return; // guard against double-inclusion
  window.__metricsTrackerLoaded = true;

  const ENDPOINT = METRICS_CONFIG.endpoint.replace(/\/$/, '') + '/events';
  const SITE_ID = METRICS_CONFIG.siteId;
  const PROJECT_KEY = METRICS_CONFIG.projectKey;

  const sessionId = sessionStorage.getItem('sid') ||
    `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  sessionStorage.setItem('sid', sessionId);

  const pageLoadTime = Date.now();

  function baseFields() {
    const fields = {
      site_id: SITE_ID,
      project_key: PROJECT_KEY,
      session_id: sessionId,
      path: location.pathname,
      referrer: document.referrer || null,
      viewport: `${window.innerWidth}x${window.innerHeight}`,
      device: /mobile/i.test(navigator.userAgent) ? 'mobile' : 'desktop'
    };

    const params = new URLSearchParams(location.search);
    if (params.has('utm_source')) {
      fields.utm = {
        source: params.get('utm_source'),
        medium: params.get('utm_medium'),
        campaign: params.get('utm_campaign')
      };
    }
    return fields;
  }

  function send(event, extra = {}) {
    const payload = { event, ...baseFields(), ...extra };
    try {
      fetch(ENDPOINT, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
        keepalive: true
      }).catch(() => {});
    } catch (_) {
      // never let a tracking failure affect the page
    }
  }

  function sendBeacon(event, extra = {}) {
    const payload = { event, ...baseFields(), ...extra };
    try {
      if (navigator.sendBeacon) {
        // Deliberately a plain string, NOT a Blob with type "application/json".
        // A plain string defaults to "text/plain;charset=UTF-8", which is a
        // CORS-simple content type — no preflight OPTIONS round-trip needed.
        // A JSON-typed Blob is NOT CORS-simple, so during page unload
        // (beforeunload/pagehide) there may not be time for the browser to
        // complete a preflight before the page is torn down, silently
        // dropping the beacon. The backend accepts this as text/plain and
        // JSON.parse()s it through the same validation pipeline.
        const ok = navigator.sendBeacon(ENDPOINT, JSON.stringify(payload));
        if (ok) return;
      }
    } catch (_) {
      // fall through to fetch fallback
    }
    send(event, extra); // fallback when sendBeacon is unavailable/fails
  }

  window.metricSend = send;

  // --- Page view (once per page load, all real pages) ---
  let pageViewSent = false;
  function sendPageViewOnce() {
    if (pageViewSent) return;
    pageViewSent = true;
    send('page_view');
  }
  if (document.readyState === 'complete' || document.readyState === 'interactive') {
    sendPageViewOnce();
  } else {
    document.addEventListener('DOMContentLoaded', sendPageViewOnce);
  }

  // --- Time on page (on exit), via sendBeacon ---
  window.addEventListener('beforeunload', () => {
    const timeSpent = Math.round((Date.now() - pageLoadTime) / 1000);
    sendBeacon('page_exit', { time_spent: timeSpent });
  });

  // --- Scroll depth (25/50/75/100%) ---
  let maxScroll = 0;
  window.addEventListener(
    'scroll',
    () => {
      const scrollable = document.documentElement.scrollHeight - window.innerHeight;
      if (scrollable <= 0) return;
      const scrollPercent = Math.round((window.scrollY / scrollable) * 100);
      if (scrollPercent > maxScroll) {
        maxScroll = scrollPercent;
        if ([25, 50, 75, 100].includes(scrollPercent)) {
          send('interaction', { interaction_event: 'scroll-depth', depth: scrollPercent });
        }
      }
    },
    { passive: true }
  );

  // --- Rage clicks + external link clicks ---
  let clickCount = 0;
  let clickTimer;

  document.addEventListener('click', (e) => {
    clickCount++;
    clearTimeout(clickTimer);
    clickTimer = setTimeout(() => { clickCount = 0; }, 1000);

    if (clickCount >= 4) {
      send('interaction', {
        interaction_event: 'rage-click',
        element: e.target.tagName,
        class: e.target.className
      });
      clickCount = 0;
    }

    const link = e.target.closest('a[href]');
    if (link && link.hostname && link.hostname !== location.hostname) {
      send('interaction', { interaction_event: 'external-link', target: link.href });
    }
  });
})();
